# Generated by Django 4.2.3 on 2023-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='dinero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_socio',
            field=models.IntegerField(default=0),
        ),
    ]
