# Generated by Django 4.2.3 on 2023-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_persona_apellidos_persona_dinero_persona_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_aportacion',
            field=models.CharField(choices=[('adulto', 'Adultos (18-66 años)'), ('jubilado', 'Adulto desde los 67 años'), ('joven', 'Jovenes (12-17 años)'), ('otro', 'Otro')], default='adulto', max_length=20),
        ),
    ]
